### GET seat count by bus
GET http://localhost:3000/api/bus/1/seatcount
Accept: application/json

### GET seat count by bus
GET http://localhost:3000/api/bus/2/seatcount
Accept: application/json

### GET seats by bus
GET http://localhost:3000/api/bus/5/seats
Accept: application/json

### GET seats by bus
GET http://localhost:3000/api/bus/5/seats?sortOrder=DESC
Accept: application/json

### UPDATE bus
DELETE http://localhost:3000/api/bus/5
Accept: application/json

{
  "capacity": 32,
  "plate_number": "223223323233"
}

### GET seats by bus
GET http://localhost:3000/api/bus/2/seats
Accept: application/json

### GET seats by bus
GET http://localhost:3000/api/bus/3
Accept: application/json

###
POST http://localhost:3000/api/bus
Accept: application/json

{
  "plate_number": "ABC_2222",
  "station_id": 1,
  "capacity": 30
}

###

GET http://localhost:3000/api/bus
Accept: application/json