### Get all cashiers
GET http://localhost:3000/api/cashier
Accept: application/json

###

### Create a new cashier
POST http://localhost:3000/api/cashier
Content-Type: application/json

{
  "first_name": "Jane",
  "last_name": "Doe",
  "user_id": 1,
  "station_id": 2
}

###

### Get a cashier by ID
GET http://localhost:3000/api/cashier/1
Accept: application/json

###

### Update a cashier by ID
PATCH http://localhost:3000/api/cashier/1
Content-Type: application/json

{
  "first_name": "Janet",
  "last_name": "Smith",
  "user_id": 1,
  "station_id": 2
}

###

### Delete a cashier by ID
DELETE http://localhost:3000/api/cashier/1
Accept: application/json
