# Get all drivers
GET http://localhost:3000/api/driver
Accept: application/json

###

# Add a new driver
POST http://localhost:3000/api/driver
Content-Type: application/json
Accept: application/json

{
  "first_name": "Test",
  "last_name": "Driver",
  "user_id": 1
}

###

# Get a driver by ID
GET http://localhost:3000/api/driver/1
Accept: application/json

###

# Update a driver by ID (partial update)
PATCH http://localhost:3000/api/driver/1
Content-Type: application/json
Accept: application/json

{
  "first_name": "Updated"
}

###

# Delete a driver by ID
DELETE http://localhost:3000/api/driver/1
Accept: application/json

###
