### GET request
GET http://localhost:3000/api/seat/1
Accept: application/json

### POST request
POST http://localhost:3000/api/seat
Content-Type: application/json

{
  "seat_number": "1D3",
  "bus_id": 1
}

### POST request
POST http://localhost:3000/api/seat
Content-Type: application/json

{
  "seat_number": "1",
  "bus_id": 2
}

### POST request
POST http://localhost:3000/api/seat
Content-Type: application/json

{
  "seat_number": "2",
  "bus_id": 1
}

### POST request
POST http://localhost:3000/api/seat
Content-Type: application/json

{
  "seat_number": "3",
  "bus_id": 1
}

### POST request
POST http://localhost:3000/api/seat
Content-Type: application/json

{
  "seat_number": "4",
  "bus_id": 1
}

### GET request
GET http://localhost:3000/api/seat/2

### DELETE request
DELETE http://localhost:3000/api/seat/151

