### Get all seats
GET http://localhost:3000/api/seat
Accept: application/json

###

### Create a new seat
POST http://localhost:3000/api/seat
Content-Type: application/json

{
  "seat_number": "A2",
  "bus_id": 4
}

###

### Get a seat by ID
GET http://localhost:3000/api/seat/1
Accept: application/json

###

### Update a seat by ID
PATCH http://localhost:3000/api/seat/15
Content-Type: application/json

{
  "seat_number": "A2",
  "status": "occupied"
}

###

### Delete a seat by ID
DELETE http://localhost:3000/api/seat/15
Accept: application/json
