### Get all stations
GET http://localhost:3000/api/station
Accept: application/json

###

### Create a new station
POST http://localhost:3000/api/station
Content-Type: application/json

{
  "name": "Terminal A"
}

###

### Get a station by ID
GET http://localhost:3000/api/station/1
Accept: application/json

###

### Update a station by ID
PATCH http://localhost:3000/api/station/1
Content-Type: application/json

{
  "name": "Terminal B"
}

###

### Delete a station by ID
DELETE http://localhost:3000/api/station/1
Accept: application/json

###

### Get a station by name
GET http://localhost:3000/api/station/name/Terminal%20A
Accept: application/json
