### Get all stations
GET http://localhost:3000/api/station
Accept: application/json

###

### Create a new station
POST http://localhost:3000/api/station
Content-Type: application/json

{
  "name": "Terminal C"
}

###

### Get a station by ID (replace `1` with actual ID)
GET http://localhost:3000/api/station/2
Accept: application/json

###

### Get a station by name (URL-encoded if needed)
GET http://localhost:3000/api/station/name/Central%20Station
Accept: application/json

### Get a station by name (URL-encoded if needed)
GET http://localhost:3000/api/station/name/Terminal%20C
Accept: application/json

###

### Delete a station by ID (replace `1` with actual ID)
DELETE http://localhost:3000/api/station/4
Accept: application/json
