### GET request
GET http://localhost:3000/api/trip
Accept: application/json

### POST request
POST http://localhost:3000/api/trip
Content-Type: application/json

{
  "start_time": "2025-07-16 08:00:00",
  "end_time": "2025-07-16 12:00:00",
  "src_station_id": 1,
  "dest_station_id": 1,
  "bus_id": 1,
  "driver_id": 1
}

###

PATCH http://localhost:3000/api/trip/31
Content-Type: application/json

{
  "status": "complete"
}

### GET request
GET http://localhost:3000/api/trip/22

### PATCH request
PATCH http://localhost:3000/api/trip/22

{
  "start_time": "2025-07-31T08:00:00Z",
  "end_time": "2025-07-31T12:00:00Z"
}


### DELETE request
DELETE http://localhost:3000/api/trip/23

###

GET http://localhost:3000/api/trip/monthly?month=7&year=2025

###

GET http://localhost:3000/api/trip/daily

###

GET http://localhost:3000/api/trip/daily?date=2025-07-31


###

GET http://localhost:3000/api/trip/daily?date=2025-07-30
