###

# Update a user by ID (partial update)
PATCH http://localhost:3000/api/user/1
Content-Type: application/json
Accept: application/json

{
  "role": "driver"
}

###

# Delete a user by ID
DELETE http://localhost:3000/api/driver/1
Accept: application/json

###

# Get all users
GET http://localhost:3000/api/user
Accept: application/json

###

# Get a user by ID
GET http://localhost:3000/api/user/1
Accept: application/json