import type { Metadata } from "next";
import NavBar from "@/components/navbar";
import { signOut } from "@/features/auth/services/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function handleSignOut() {
  "use server";
  await signOut({ redirectTo: "/signOut" });
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <NavBar handleSignOut={handleSignOut}></NavBar>

      {children}
    </div>
  );
}
